services:
  main_backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python3 main.py'
    container_name: main_backend
    ports: 
      - "8001:5001"
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: . 
      dockerfile: Dockerfile 
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    container_name: main_db
    restart: always
    env_file:
      - .env
    volumes:
      - .dbdata:/lix/mysql
    ports:
      - "3304:3306"
