services:

  store:
    container_name: store
    build:
      context: ./django_fakestore
      dockerfile: Dockerfile
    env_file:
      - .env 
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - fakestore 
    volumes:
      - ./django_fakestore:/app
    restart: always

  db:
    image: postgres:16
    container_name: fakestore_db
    env_file:
      - .env 
    networks:
      - fakestore
    volumes:
      - fakestore_data:/var/lib/postgresql/data/

networks:
  fakestore:

volumes:
  fakestore_data:
