services:

  store:
    container_name: store
    build:
      context: ./django_fakestore
      dockerfile: Dockerfile
    env_file:
      - .env 
    expose:
      - 8001
    depends_on:
      - db
    networks:
      - fakestore 
    volumes:
      - ./django_fakestore:/app
    restart: always

  db:
    image: postgres:16
    container_name: fakestore_db
    env_file:
      - .env 
    networks:
      - fakestore
    volumes:
      - fakestore_data:/var/lib/postgresql/data/
  
  modsec_apache:
    container_name: modsec-apache
    build:
      context: ./modsec_apache 
      dockerfile: Dockerfile
    env_file:
      - .env 
    ports:
      - "443:443"
    networks:
      - fakestore

  # modsec_nginx:
  #   container_name: httpserver
  #   build:
  #     context: ./modsec_nginx
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - "8443"
  #   restart: always
  #   depends_on: 
  #       - db 



networks:
  fakestore:

volumes:
  fakestore_data:
