services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    command: 'python ./tutorial/manage.py runserver 0.0.0.0:8000' 
    env_file:
      - .env
    volumes:
      - .:/app 
    depends_on:
      - db
  queue:
    build:
      context: . 
      dockerfile: Dockerfile 
    command: 'python ./tutorial/consumer.py'
    depends_on:
      - db


  db:
    image: mysql:5.7.22
    container_name: backend_db
    restart: always
    env_file:
      - .env
    volumes:
      - .dbdata:/lib/mysql
    ports:
      - "3305:3306"
