services:
  user_management:
    container_name: user_management
    build:
      context: ./application/docker/user_management/
    depends_on:
      - database
    restart: unless-stopped
    env_file:
      - .user_management.env
    ports:
      - "8001:8000"
    volumes:
      - ./application/service:/app/
  
  user_man_database:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .user_management.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # nginx:
  #   container_name: nginx 
  #   build: ./utils/nginx/
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   depends_on:
  #     - django
  #   restart: unless-stopped
  #

networks:
  experience:
    name: experience

volumes:
  postgres_data:
    name: postgres_data
